CREATE TABLE "merchant_canonical_map" (
	"merchant_key" uuid PRIMARY KEY NOT NULL,
	"canonical_merchant_key" uuid NOT NULL,
	"uniq_merchant" text NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "merchant_feedback" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "merchant_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"merchant_key" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"type" text NOT NULL,
	"category" text NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"reply" text,
	"replied_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "merchant_feedback_type_check" CHECK ("merchant_feedback"."type" in ('report', 'critic', 'suggestion')),
	CONSTRAINT "merchant_feedback_status_check" CHECK ("merchant_feedback"."status" in ('open', 'in_progress', 'resolved'))
);
--> statement-breakpoint
CREATE TABLE "merchant_users" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"merchant_key" uuid NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "merchant_users_user_id_merchant_key_unique" UNIQUE("user_id","merchant_key")
);
--> statement-breakpoint
CREATE TABLE "provider_banners" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provider_banners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"image_key" text NOT NULL,
	"title" text NOT NULL,
	"subtitle" text NOT NULL,
	"cta" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"username" text,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'merchant' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_role_check" CHECK ("users"."role" in ('merchant', 'admin'))
);
--> statement-breakpoint
ALTER TABLE "merchant_feedback" ADD CONSTRAINT "merchant_feedback_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "merchant_users" ADD CONSTRAINT "merchant_users_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_merchant_feedback_merchant" ON "merchant_feedback" USING btree ("merchant_key");--> statement-breakpoint
CREATE INDEX "idx_merchant_feedback_user" ON "merchant_feedback" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_merchant_feedback_status" ON "merchant_feedback" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_merchant_users_merchant_key" ON "merchant_users" USING btree ("merchant_key");--> statement-breakpoint
CREATE INDEX "idx_provider_banners_active" ON "provider_banners" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_provider_banners_sort" ON "provider_banners" USING btree ("sort_order");